package io.github.derekh_233.watranslate;

import android.content.Context;
import android.os.Handler;
import android.os.Looper;

import org.json.JSONObject;

import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TimeZone;

/**
 * Offline contact-locale intelligence: country, language, currency and local
 * time, derived from the peer's phone number.
 *
 * Data comes from two tables bundled in assets, both generated by
 * tools/gen_locale_data.py from public sources (IANA/CLDR/ISO data sets):
 *   languages.json - 563 languages, {code: {zh, en}}
 *   regions.json   - 203 dialling codes, {code: {cc, country, lang, tz, cur}}
 * Both are loaded once, synchronously (~60 KB total).
 */
public final class LocaleInfo {

    public static final class Info {
        public final String areaCode;
        public final String country;
        public final String languageLabel;
        public final String langCode;
        public final String timeZone;
        public final String currency;
        public final String localTime;

        Info(String areaCode, String country, String languageLabel, String langCode,
             String timeZone, String currency, String localTime) {
            this.areaCode = areaCode;
            this.country = country;
            this.languageLabel = languageLabel;
            this.langCode = langCode;
            this.timeZone = timeZone;
            this.currency = currency;
            this.localTime = localTime;
        }

        public boolean isEmpty() {
            return areaCode == null && languageLabel == null;
        }
    }

    private static final Map<String, JSONObject> AREA = new HashMap<String, JSONObject>();
    private static final Map<String, JSONObject> LANG = new HashMap<String, JSONObject>();
    private static final Map<String, String> SYMBOL = currencySymbols();
    private static volatile boolean loaded;

    private LocaleInfo() {
    }

    public static synchronized void load(Context ctx) {
        if (loaded) {
            return;
        }
        loaded = true;
        try {
            JSONObject area = new JSONObject(readAsset(ctx, "regions.json"));
            Iterator<String> it = area.keys();
            while (it.hasNext()) {
                String k = it.next();
                AREA.put(k.replace("+", ""), area.optJSONObject(k));
            }
            JSONObject lang = new JSONObject(readAsset(ctx, "languages.json"));
            Iterator<String> it2 = lang.keys();
            while (it2.hasNext()) {
                String k = it2.next();
                LANG.put(k.toLowerCase(Locale.US), lang.optJSONObject(k));
            }
            Logger.d("locale tables loaded: " + AREA.size() + " dialling codes, "
                    + LANG.size() + " languages");
        } catch (Throwable t) {
            Logger.w("locale table load failed: " + t);
        }
    }

    private static String readAsset(Context ctx, String name) throws Exception {
        InputStream in = ctx.getAssets().open(name);
        java.io.ByteArrayOutputStream bos = new java.io.ByteArrayOutputStream();
        byte[] buf = new byte[8192];
        int n;
        while ((n = in.read(buf)) > 0) {
            bos.write(buf, 0, n);
        }
        in.close();
        // strip BOM if present
        byte[] all = bos.toByteArray();
        int start = (all.length > 3 && (all[0] & 0xFF) == 0xEF && (all[1] & 0xFF) == 0xBB
                && (all[2] & 0xFF) == 0xBF) ? 3 : 0;
        return new String(all, start, all.length - start, "UTF-8");
    }

    // ------------------------------------------------------------- languages

    /** All languages as [code, labelZh, labelEn] - used by the picker. */
    public static List<String[]> allLanguages() {
        List<String[]> out = new ArrayList<String[]>(LANG.size());
        for (Map.Entry<String, JSONObject> e : LANG.entrySet()) {
            JSONObject o = e.getValue();
            out.add(new String[]{
                    e.getKey(),
                    o == null ? e.getKey() : o.optString("zh", e.getKey()),
                    o == null ? e.getKey() : o.optString("en", e.getKey()),
            });
        }
        sortByDisplay(out);
        return out;
    }

    public static List<String[]> allAreaCodes() {
        List<String[]> out = new ArrayList<String[]>(AREA.size());
        for (Map.Entry<String, JSONObject> e : AREA.entrySet()) {
            JSONObject o = e.getValue();
            String label = o == null ? "" : o.optString("language", "");
            out.add(new String[]{"+" + e.getKey(), label});
        }
        sortByDisplay(out);
        return out;
    }

    private static void sortByDisplay(List<String[]> list) {
        Collections.sort(list, new Comparator<String[]>() {
            @Override
            public int compare(String[] a, String[] b) {
                String x = a.length > 1 ? a[1] : a[0];
                String y = b.length > 1 ? b[1] : b[0];
                return x.compareToIgnoreCase(y);
            }
        });
    }

    public static String labelOf(String code) {
        if (code == null) {
            return null;
        }
        JSONObject o = LANG.get(code.toLowerCase(Locale.US));
        if (o == null) {
            String base = code.contains("-") ? code.substring(0, code.indexOf('-')) : code;
            o = LANG.get(base.toLowerCase(Locale.US));
        }
        return o == null ? code : o.optString("zh", code);
    }

    // ----------------------------------------------------------------- peer

    /** Longest-prefix match against the 215 calling codes. */
    static String matchAreaCode(String phone) {
        if (phone == null) {
            return null;
        }
        String digits = phone.replaceAll("[^0-9]", "");
        if (digits.isEmpty()) {
            return null;
        }
        String best = null;
        for (String k : AREA.keySet()) {
            if (digits.startsWith(k) && (best == null || k.length() > best.length())) {
                best = k;
            }
        }
        return best;
    }

    /** Build the locale card for a raw phone number, or null when unknown. */
    public static Info forPhone(String phone) {
        if (phone == null) {
            return null;
        }
        String cc = matchAreaCode(phone);
        if (cc == null) {
            return null;
        }
        JSONObject o = AREA.get(cc);
        if (o == null) {
            return null;
        }
        String tz = o.optString("tz", "");
        String currency = o.optString("cur", "");
        String langCode = o.optString("lang", "");
        return new Info("+" + cc, o.optString("country", ""), labelOf(langCode),
                langCode, tz, currency, localTime(tz));
    }

    static String localTime(String timeZoneId) {
        if (timeZoneId == null || timeZoneId.isEmpty()) {
            return null;
        }
        try {
            SimpleDateFormat f = new SimpleDateFormat("HH:mm", Locale.US);
            f.setTimeZone(TimeZone.getTimeZone(timeZoneId));
            return f.format(new Date());
        } catch (Throwable t) {
            return null;
        }
    }

    public static String currencySymbol(String code) {
        if (code == null) {
            return "";
        }
        String s = SYMBOL.get(code.toUpperCase(Locale.US));
        return s == null ? code : s;
    }

    /** One-line card, e.g. "+44 英国 · 英语 · GBP £ · 18:32". */
    public static String describe(Info info) {
        if (info == null || info.isEmpty()) {
            return null;
        }
        StringBuilder sb = new StringBuilder();
        sb.append(info.areaCode == null ? "?" : info.areaCode);
        if (info.country != null && !info.country.isEmpty()) {
            sb.append(' ').append(info.country);
        }
        if (info.languageLabel != null) {
            sb.append(" · ").append(info.languageLabel);
        }
        if (info.currency != null && !info.currency.isEmpty()) {
            sb.append(" · ").append(info.currency)
                    .append(' ').append(currencySymbol(info.currency));
        }
        if (info.localTime != null) {
            sb.append(" · ").append(info.localTime);
        }
        if (info.timeZone != null && !info.timeZone.isEmpty()) {
            sb.append(" (").append(info.timeZone).append(')');
        }
        return sb.toString();
    }

    private static Map<String, String> currencySymbols() {
        Map<String, String> m = new HashMap<String, String>();
        String[][] raw = {
                {"USD", "$"}, {"EUR", "€"}, {"GBP", "£"}, {"JPY", "¥"}, {"CNY", "¥"},
                {"KRW", "₩"}, {"INR", "₹"}, {"RUB", "₽"}, {"BRL", "R$"}, {"TRY", "₺"},
                {"THB", "฿"}, {"VND", "₫"}, {"IDR", "Rp"}, {"MYR", "RM"}, {"PHP", "₱"},
                {"SGD", "S$"}, {"HKD", "HK$"}, {"TWD", "NT$"}, {"AUD", "A$"}, {"CAD", "C$"},
                {"CHF", "CHF"}, {"SEK", "kr"}, {"NOK", "kr"}, {"DKK", "kr"}, {"PLN", "zł"},
                {"MXN", "MX$"}, {"ARS", "AR$"}, {"ZAR", "R"}, {"AED", "د.إ"}, {"SAR", "﷼"},
                {"EGP", "E£"}, {"NGN", "₦"}, {"KES", "KSh"}, {"PKR", "₨"}, {"BDT", "৳"},
                {"LKR", "Rs"}, {"NPR", "₨"}, {"ILS", "₪"}, {"UAH", "₴"}, {"CZK", "Kč"},
                {"HUF", "Ft"}, {"RON", "lei"}, {"BGN", "лв"}, {"HRK", "kn"}, {"ISK", "kr"},
                {"NZD", "NZ$"}, {"CLP", "CL$"}, {"COP", "CO$"}, {"PEN", "S/"}, {"UYU", "$U"},
        };
        for (String[] p : raw) {
            m.put(p[0], p[1]);
        }
        return Collections.unmodifiableMap(m);
    }
}
